import { Metadata } from "next";
import WelcomePageContainer from "./components";

export const metadata: Metadata = {
  title: "Welcome Page",
  description: "Generated by create next app",
};

export default function Welcome() {
  return <WelcomePageContainer />;
}
