import { Metadata } from "next";
import WelcomePageContainer from "./components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Welcome() {
  return <WelcomePageContainer />;
}
